<Project Sdk="Godot.NET.Sdk/4.6.1">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Fodot.Async</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="GodotObject.fs" />
        <Compile Include="GD.fs" />
        <Compile Include="GDTask.fs" />
        <Compile Include="AsyncScene.fs" />
        <Compile Include="AsyncNode.fs" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Fodot.Core\Fodot.Core.fsproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="GDTask" Version="3.0.0" />
    </ItemGroup>

</Project>
