<Project Sdk="Godot.NET.Sdk/4.6.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>GodotCSharp</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Fodot.Generator\Fodot.Generator.fsproj" />
    <ProjectReference Include="..\Fodot\Fodot.fsproj" />
    <ProjectReference Include="..\Fodot.Test\Fodot.Test.fsproj" />
  </ItemGroup>
</Project>