<Project Sdk="Godot.NET.Sdk/4.6.1">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Fodot</RootNamespace>
    </PropertyGroup>

    <Target Name="CreateBinding" BeforeTargets="BeforeBuild">
        <Exec Command="dotnet run --project ../Fodot.Generator/Fodot.Generator.fsproj -- ../project Bind.fs" />
    </Target>

    <ItemGroup>
        <PackageReference Include="GDTask" Version="3.0.0" />
        <PackageReference Include="FSharpPlus" Version="1.9.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Godot.Bridge\Godot.Bridge.csproj" />
    </ItemGroup>

    <ItemGroup>
        <Compile Include="Common\Attribute.fs" />
        <Compile Include="Common\Logger.fs" />
        <Compile Include="Common\Singleton.fs" />
        <Compile Include="Core\Variant.fs" />
        <Compile Include="Core\Callable.fs" />
        <Compile Include="Core\GodotObject.fs" />
        <Compile Include="Core\GD.fs" />
        <Compile Include="Core\FScript.fs" />
        <Compile Include="Core\Node.fs" />
        <Compile Include="Core\PackedScene.fs" />
        <Compile Include="Core\Engine.fs" />
        <Compile Include="Bind.fs" />
        <Compile Include="Library\Library.fs" />
    </ItemGroup>

    <Import Project="..\project\library\library.props" />

    <ItemGroup>
        <Compile Include="Async\GDTask.fs" />
        <Compile Include="Async\GodotObject.fs" />
        <Compile Include="Async\GD.fs" />
        <Compile Include="Async\Tween.fs" />
        <Compile Include="Async\AsyncScene.fs" />
        <Compile Include="Async\AsyncNode.fs" />
        <Compile Include="Module\Vector2.fs" />
        <Compile Include="Module\Color.fs" />
        <Compile Include="Module\Transform2D.fs" />
        <Compile Include="Module\CanvasItem.fs" />
        <Compile Include="Module\Tween.fs" />
        <Compile Include="System\Cutscene.fs" />
        <Compile Include="System\Stage.fs" />
    </ItemGroup>

</Project>
