<Project Sdk="Godot.NET.Sdk/4.6.1">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <RootNamespace>Fodot.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Variant.fs" />
        <Compile Include="GodotObject.fs" />
        <Compile Include="GD.fs" />
        <Compile Include="FScript.fs" />
        <Compile Include="Node.fs" />
        <Compile Include="PackedScene.fs" />
        <Compile Include="Engine.fs" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Fodot.Common\Fodot.Common.fsproj" />
      <ProjectReference Include="..\Godot.Bridge\Godot.Bridge.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="FSharpPlus" Version="1.9.1" />
    </ItemGroup>

</Project>
