@tool
extends Resource
class_name Library

@export_category("Library")
@export_tool_button("Generate") var generate = _generate
@export var lib_name : String = ""
@export var lib : Dictionary[String, Resource] = {}

const FS_PROJ : String = "res://library/library.props"
const FS_PROJ_ITEM = "<Compile Include=\"..\\project\\library\\%s\">"
const FS_PROJ_LINK = "<Link>Library\\%s</Link>"

func get_lib_name():
	if lib_name == "":
		return resource_path.get_file().get_basename().to_pascal_case()
	return lib_name

func get_fs_name():
	return get_lib_name() + ".fs"

func create_fs_file():
	var library = get_lib_name()
	var fs = get_fs_name()
	var id = ResourceLoader.get_resource_uid(resource_path)
	var id_text = ResourceUID.id_to_text(id)
	var f = FileAccess.open(FS_PROJ.get_base_dir() + "/" + fs, FileAccess.WRITE)
	f.store_line("// %s" % resource_path)
	f.store_line("// Auto generated by resource library. DO NOT EDIT.\n")
	f.store_line("module Fodot.Library." + library + "\n")
	f.store_line("open Godot\n")
	f.store_line("let private _back_lib = GDLib(\"%s\")\n" % id_text)
	var all = ""
	for k in lib.keys():
		var v = lib[k]
		var type = v.get_class()
		var kname = k.to_camel_case()
		if all != "": all += "; "
		all += kname
		f.store_line("let %s = _back_lib.Get<%s>(\"%s\")\n" % [kname, type, k])
	f.store_line("let lib = _back_lib.Lib")
	f.store_line("let all : Resource list = [%s]" % all)
	f.close()

static func get_compile_item(fs):
	var fs_compile = FS_PROJ_ITEM % fs
	var fs_link = FS_PROJ_LINK % fs
	return "\n\t\t" + fs_compile + "\n\t\t\t" + fs_link + "\n\t\t</Compile>"

static func update_props():
	var f = FileAccess.open(FS_PROJ, FileAccess.WRITE)
	f.store_line("<Project>")
	f.store_line("\t<ItemGroup>")
	var d = DirAccess.open(FS_PROJ.get_base_dir())
	for file in d.get_files():
		if file.get_extension() != "fs":
			continue
		var item = FS_PROJ_ITEM % file
		var link = FS_PROJ_LINK % file
		f.store_line("\t\t" + item)
		f.store_line("\t\t\t" + link)
		f.store_line("\t\t</Compile>")
	d.list_dir_end()
	f.store_line("\t</ItemGroup>")
	f.store_line("</Project>")
	f.close()

func _generate():
	create_fs_file()
	update_props()